### ISSUE TITLE
Audio cannot pause using control center when play in background

### ISSUE THREAD

**Issue by frannnnk** [AubreyHewes/cordova-background-audio#5]
Great plugin, really a must have plugin when developing audio player using ionic.
I found that the audio can be played in background, however it cannot be controlled using control center when playing in background, when click the pause button in control center the music still playing.

**Comment by elloboblanco** [comment]
@frannnnk try using https://github.com/shi11/RemoteControls

**Comment by frannnnk** [comment]
@elloboblanco Thanks for the tips, i will add it to my project :)

**Comment by Heshyo** [comment]
@frannnnk I'm using Ionic2 with `cordova-plugin-media` and whenever I go out of the app, the audio stops. What are you using? I'm on iOS 9.3.2.

**Comment by AubreyHewes** [comment]
Sorry, I am not actively developing this project (it still works for the original customer). See the readme.
I am open to pr/contributors. See the readme.

**Comment by Heshyo** [comment]
For anyone interested, this is what I ended up using in a specific project:
- https://github.com/EddyVerbruggen/cordova-plugin-backgroundaudio#1.0.1 to continue playing in the background (instead of this plugin as it didn't seem to work)
- https://www.npmjs.com/package/cordova-plugin-nowplaying to show the currently playing media on the lock screen
- https://www.npmjs.com/package/cordova-plugin-remotecommand to add commands on the lock screen (play, pause, next, ...)
